"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 13:30:47.513856
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_clusters',
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('centroid', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_clusters'))
    )
    op.create_table('models',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('experiment_configs',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_experiment_configs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_configs'))
    )
    with op.batch_alter_table('experiment_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_configs_owner_id'), ['owner_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=120), nullable=False),
    sa.Column('revision', sa.String(length=120), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name=op.f('fk_model_versions_model_id_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_id', 'version_label', name=op.f('uq_model_versions_model_id'))
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_model_id'), ['model_id'], unique=False)

    op.create_table('experiments',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('evaluator', sa.String(length=80), nullable=False),
    sa.Column('dataset_name', sa.String(length=120), nullable=True),
    sa.Column('dataset_version', sa.String(length=60), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('software_version', sa.String(length=40), nullable=False),
    sa.Column('environment', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['experiment_configs.id'], name=op.f('fk_experiments_config_id_experiment_configs')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_experiments_model_version_id_model_versions')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_experiments_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_experiments_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_task_type'), ['task_type'], unique=False)
        batch_op.create_index('ix_experiments_type_model', ['task_type', 'model_version_id'], unique=False)

    op.create_table('experiment_runs',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('run_index', sa.Integer(), nullable=False),
    sa.Column('variant_label', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_runs_experiment_id_experiments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_runs')),
    sa.UniqueConstraint('experiment_id', 'run_index', name=op.f('uq_experiment_runs_experiment_id'))
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_runs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_status'), ['status'], unique=False)

    op.create_table('metrics',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('dimension', sa.String(length=1), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ci_low', sa.Float(), nullable=True),
    sa.Column('ci_high', sa.Float(), nullable=True),
    sa.Column('ci_level', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=120), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_metrics_experiment_id_experiments')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_metrics_model_version_id_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_dimension'), ['dimension'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_name'), ['name'], unique=False)

    op.create_table('reports',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('experiment_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('includes_demo_data', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_reports_experiment_id_experiments')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_reports_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_owner_id'), ['owner_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('evaluator_name', sa.String(length=80), nullable=False),
    sa.Column('evaluator_version', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('judge_model', sa.String(length=200), nullable=True),
    sa.Column('judge_prompt', sa.Text(), nullable=True),
    sa.Column('judge_version', sa.String(length=60), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_evaluations_run_id_experiment_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_evaluator_name'), ['evaluator_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_run_id'), ['run_id'], unique=False)

    op.create_table('experiment_lineage',
    sa.Column('parent_experiment_id', sa.Uuid(), nullable=False),
    sa.Column('child_experiment_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_run_id', sa.Uuid(), nullable=True),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_experiment_id'], ['experiments.id'], name=op.f('fk_experiment_lineage_child_experiment_id_experiments')),
    sa.ForeignKeyConstraint(['parent_experiment_id'], ['experiments.id'], name=op.f('fk_experiment_lineage_parent_experiment_id_experiments')),
    sa.ForeignKeyConstraint(['trigger_run_id'], ['experiment_runs.id'], name=op.f('fk_experiment_lineage_trigger_run_id_experiment_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_lineage')),
    sa.UniqueConstraint('parent_experiment_id', 'child_experiment_id', name=op.f('uq_experiment_lineage_parent_experiment_id'))
    )
    with op.batch_alter_table('experiment_lineage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_lineage_child_experiment_id'), ['child_experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_lineage_parent_experiment_id'), ['parent_experiment_id'], unique=False)

    op.create_table('failure_modes',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('detector', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.id'], name=op.f('fk_failure_modes_cluster_id_failure_clusters')),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_failure_modes_run_id_experiment_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failure_modes'))
    )
    with op.batch_alter_table('failure_modes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failure_modes_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_modes_label'), ['label'], unique=False)
        batch_op.create_index(batch_op.f('ix_failure_modes_run_id'), ['run_id'], unique=False)

    op.create_table('metric_evidence',
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], name=op.f('fk_metric_evidence_metric_id_metrics')),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_metric_evidence_run_id_experiment_runs')),
    sa.PrimaryKeyConstraint('metric_id', 'run_id', name=op.f('pk_metric_evidence'))
    )
    with op.batch_alter_table('metric_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_evidence_run_id'), ['run_id'], unique=False)

    op.create_table('prompts',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('system_text', sa.Text(), nullable=True),
    sa.Column('variant_kind', sa.String(length=60), nullable=False),
    sa.Column('variant_params', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_prompts_run_id_experiment_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('run_id', name=op.f('uq_prompts_run_id'))
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_content_hash'), ['content_hash'], unique=False)

    op.create_table('responses',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('finish_reason', sa.String(length=40), nullable=True),
    sa.Column('is_empty', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], name=op.f('fk_responses_run_id_experiment_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responses')),
    sa.UniqueConstraint('run_id', name=op.f('uq_responses_run_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_content_hash'))

    op.drop_table('prompts')
    with op.batch_alter_table('metric_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_evidence_run_id'))

    op.drop_table('metric_evidence')
    with op.batch_alter_table('failure_modes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failure_modes_run_id'))
        batch_op.drop_index(batch_op.f('ix_failure_modes_label'))
        batch_op.drop_index(batch_op.f('ix_failure_modes_cluster_id'))

    op.drop_table('failure_modes')
    with op.batch_alter_table('experiment_lineage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_lineage_parent_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_lineage_child_experiment_id'))

    op.drop_table('experiment_lineage')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_run_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_evaluator_name'))

    op.drop_table('evaluations')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_owner_id'))
        batch_op.drop_index(batch_op.f('ix_reports_experiment_id'))

    op.drop_table('reports')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_name'))
        batch_op.drop_index(batch_op.f('ix_metrics_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_dimension'))

    op.drop_table('metrics')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_runs_status'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_experiment_id'))

    op.drop_table('experiment_runs')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index('ix_experiments_type_model')
        batch_op.drop_index(batch_op.f('ix_experiments_task_type'))
        batch_op.drop_index('ix_experiments_status_created')
        batch_op.drop_index(batch_op.f('ix_experiments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_model_version_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_model_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('experiment_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_configs_owner_id'))

    op.drop_table('experiment_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_slug'))
        batch_op.drop_index(batch_op.f('ix_models_provider'))

    op.drop_table('models')
    op.drop_table('failure_clusters')
    # ### end Alembic commands ###
