"""cluster owner

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 16:20:49.757638
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failure_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_failure_clusters_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_failure_clusters_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('failure_clusters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_failure_clusters_owner_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_failure_clusters_owner_id'))
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
