"""notebook and report links

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 21:27:37.531560
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_investigations_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_owner_id'), ['owner_id'], unique=False)

    op.create_table('investigation_notes',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_notes_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_notes'))
    )
    with op.batch_alter_table('investigation_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_notes_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('investigation_experiments',
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_investigation_experiments_experiment_id_experiments')),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_experiments_investigation_id_investigations')),
    sa.PrimaryKeyConstraint('investigation_id', 'experiment_id', name=op.f('pk_investigation_experiments'))
    )
    with op.batch_alter_table('investigation_experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_experiments_experiment_id'), ['experiment_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investigation_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_reports_investigation_id_investigations'), 'investigations', ['investigation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reports_investigation_id_investigations'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_investigation_id'))
        batch_op.drop_column('investigation_id')

    with op.batch_alter_table('investigation_experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_experiments_experiment_id'))

    op.drop_table('investigation_experiments')
    with op.batch_alter_table('investigation_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_notes_investigation_id'))

    op.drop_table('investigation_notes')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_owner_id'))

    op.drop_table('investigations')
    # ### end Alembic commands ###
